
using Hangfire.Dashboard;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Extensions
{
    public class MyAuthorizationFilter : IDashboardAuthorizationFilter
    {


        public bool Authorize(DashboardContext context)
        {

            if (HttpContext.Current.Session == null)
            {
                // Session is always null for requests generated by clicking on a job
                return false;
            }
            //some other case:
            return true;
        }
    }
}
